#!/usr/bin/env php
<?php

// Check PHP version
if (!version_compare(phpversion(), '8.3.0', '>=')) {
	echo "\e[31mPHP 8.3+ is required to run FreeScout.\e[0m\n";
	exit();
}

define('LARAVEL_START', microtime(true));

require __DIR__.'/vendor/autoload.php';

$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
