<?php
/**
 * Laravel 5.5 legacy model factory was removed in Laravel 8.
 * Module service providers generated by nwidart/laravel-modules call
 * app(\Illuminate\Database\Eloquent\Factory::class)->load($path) in non-production environments.
 * This class keeps such modules working. Legacy factory definitions are not loaded.
 */

namespace Illuminate\Database\Eloquent;

class Factory
{
    public function load($path)
    {
        return $this;
    }

    public function __call($method, $parameters)
    {
        return $this;
    }
}
